version: '3.4'

services:
    php:
        image: php:8-fpm
        working_dir: /app
        user: ${UID:-1000}:${GID:-1000}
        volumes:
          - ${PWD}:/app
          - ${HOME}/.composer:/.composer
        environment:
          - COMPOSER_ALLOW_SUPERUSER=1